const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAIL: 'FETCH_GENDER_FAIL',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAIL: 'FETCH_POSITION_FAIL',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAIL: 'FETCH_ROLE_FAIL',

    //CRUD User
    CREATE_USER_START: 'CREATE_USER_START',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    FETCH_ALL_USER_START: 'FETCH_ALL_USER_START',
    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAIL: 'FETCH_ALL_USER_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',

    //Doctor
    FETCH_TOP_DOCTOR_START: 'FETCH_TOP_DOCTOR_START',
    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAIL: 'FETCH_TOP_DOCTOR_FAIL',

    FETCH_ALL_DOCTOR_START: 'FETCH_ALL_DOCTOR_START',
    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAIL: 'FETCH_ALL_DOCTOR_FAIL',

    SAVE_DETAIL_DOCTOR_SUCCESS: 'SAVE_DETAIL_DOCTOR_SUCCESS',
    SAVE_DETAIL_DOCTOR_FAIL: 'SAVE_DETAIL_DOCTOR_FAIL',

    GET_DETAIL_DOCTOR_SUCCESS: 'GET_DETAIL_DOCTOR_SUCCESS',
    GET_DETAIL_DOCTOR_FAIL: 'GET_DETAIL_DOCTOR_FAIL',

    UPDATE_INFO_DOCTOR_SUCCESS: 'UPDATE_INFO_DOCTOR_SUCCESS',
    UPDATE_INFO_DOCTOR_FAIL: 'UPDATE_INFO_DOCTOR_FAIL',

    FETCH_ALLCODE_HOURS_SUCCESS: 'FETCH_ALLCODE_HOURS_SUCCESS',
    FETCH_ALLCODE_HOURS_FAIL: 'FETCH_ALLCODE_HOURS_FAIL',

    SAVE_SCHEDULE_DOCTOR_SUCCESS: 'SAVE_SCHEDULE_DOCTOR_SUCCESS',
    SAVE_SCHEDULE_DOCTOR_FAIL: 'SAVE_SCHEDULE_DOCTOR_FAIL',

    FETCH_SCHEDULE_DOCTOR_SUCCESS: 'FETCH_SCHEDULE_DOCTOR_SUCCESS',
    FETCH_SCHEDULE_DOCTOR_FAIL: 'FETCH_SCHEDULE_DOCTOR_FAIL',

    FETCH_ALL_PRICE_SUCCESS: 'FETCH_ALL_PRICE_SUCCESS',
    FETCH_ALL_PRICE_FAIL: 'FETCH_ALL_PRICE_FAIL',

    FETCH_ALL_PROVINCE_SUCCESS: 'FETCH_ALL_PROVINCE_SUCCESS',
    FETCH_ALL_PROVINCE_FAIL: 'FETCH_ALL_PROVINCE_FAIL',

    FETCH_ALL_PAYMENT_SUCCESS: 'FETCH_ALL_PAYMENT_SUCCESS',
    FETCH_ALL_PAYMENT_FAIL: 'FETCH_ALL_PAYMENT_FAIL',

    FETCH_EXTRA_INFO_DOCTOR_SUCCESS: 'FETCH_EXTRA_INFO_DOCTOR_SUCCESS',
    FETCH_EXTRA_INFO_DOCTOR_FAIL: 'FETCH_EXTRA_INFO_DOCTOR_FAIL',

    FETCH_PROFILE_DOCTOR_SUCCESS: 'FETCH_PROFILE_DOCTOR_SUCCESS',
    FETCH_PROFILE_DOCTOR_FAIL: 'FETCH_PROFILE_DOCTOR_FAIL',

})

export default actionTypes;